package co.edu.campusucc.sd.modelo;
// Generated 23/05/2020 02:30:18 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Banco generated by hbm2java
 */
public class Banco implements java.io.Serializable {

	private String idBanco;
	private String nombreBanco;
	private String direccion;
	private String email;
	private Set clientes = new HashSet(0);

	public Banco() {
	}

	public Banco(String idBanco, String nombreBanco, String direccion, String email) {
		this.idBanco = idBanco;
		this.nombreBanco = nombreBanco;
		this.direccion = direccion;
		this.email = email;
	}

	public Banco(String idBanco, String nombreBanco, String direccion, String email, Set clientes) {
		this.idBanco = idBanco;
		this.nombreBanco = nombreBanco;
		this.direccion = direccion;
		this.email = email;
		this.clientes = clientes;
	}

	public String getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(String idBanco) {
		this.idBanco = idBanco;
	}

	public String getNombreBanco() {
		return this.nombreBanco;
	}

	public void setNombreBanco(String nombreBanco) {
		this.nombreBanco = nombreBanco;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
