package co.edu.campusucc.sd.modelo;
// Generated 23/05/2020 02:30:18 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

	private String idCliente;
	private Banco banco;
	private TipoCliente tipoCliente;
	private TipoDocumento tipoDocumento;
	private String nombre;
	private String apellidos;
	private Set cuentas = new HashSet(0);

	public Cliente() {
	}

	public Cliente(String idCliente, String nombre, String apellidos) {
		this.idCliente = idCliente;
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	public Cliente(String idCliente, Banco banco, TipoCliente tipoCliente, TipoDocumento tipoDocumento, String nombre,
			String apellidos, Set cuentas) {
		this.idCliente = idCliente;
		this.banco = banco;
		this.tipoCliente = tipoCliente;
		this.tipoDocumento = tipoDocumento;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.cuentas = cuentas;
	}

	public String getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(String idCliente) {
		this.idCliente = idCliente;
	}

	public Banco getBanco() {
		return this.banco;
	}

	public void setBanco(Banco banco) {
		this.banco = banco;
	}

	public TipoCliente getTipoCliente() {
		return this.tipoCliente;
	}

	public void setTipoCliente(TipoCliente tipoCliente) {
		this.tipoCliente = tipoCliente;
	}

	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
