package co.edu.campusucc.sd.modelo;
// Generated 23/05/2020 02:30:18 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta implements java.io.Serializable {

	private String idCuenta;
	private Cliente cliente;
	private TipoCuenta tipoCuenta;
	private String referenciaCliente;
	private Set transferenciases = new HashSet(0);

	public Cuenta() {
	}

	public Cuenta(String idCuenta, String referenciaCliente) {
		this.idCuenta = idCuenta;
		this.referenciaCliente = referenciaCliente;
	}

	public Cuenta(String idCuenta, Cliente cliente, TipoCuenta tipoCuenta, String referenciaCliente,
			Set transferenciases) {
		this.idCuenta = idCuenta;
		this.cliente = cliente;
		this.tipoCuenta = tipoCuenta;
		this.referenciaCliente = referenciaCliente;
		this.transferenciases = transferenciases;
	}

	public String getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(String idCuenta) {
		this.idCuenta = idCuenta;
	}

	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	public TipoCuenta getTipoCuenta() {
		return this.tipoCuenta;
	}

	public void setTipoCuenta(TipoCuenta tipoCuenta) {
		this.tipoCuenta = tipoCuenta;
	}

	public String getReferenciaCliente() {
		return this.referenciaCliente;
	}

	public void setReferenciaCliente(String referenciaCliente) {
		this.referenciaCliente = referenciaCliente;
	}

	public Set getTransferenciases() {
		return this.transferenciases;
	}

	public void setTransferenciases(Set transferenciases) {
		this.transferenciases = transferenciases;
	}

}
