package co.edu.campusucc.sd.modelo;
// Generated 23/05/2020 02:30:18 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoDocumento generated by hbm2java
 */
public class TipoDocumento implements java.io.Serializable {

	private String idTipoDocumento;
	private String nombre;
	private Set clientes = new HashSet(0);

	public TipoDocumento() {
	}

	public TipoDocumento(String idTipoDocumento, String nombre) {
		this.idTipoDocumento = idTipoDocumento;
		this.nombre = nombre;
	}

	public TipoDocumento(String idTipoDocumento, String nombre, Set clientes) {
		this.idTipoDocumento = idTipoDocumento;
		this.nombre = nombre;
		this.clientes = clientes;
	}

	public String getIdTipoDocumento() {
		return this.idTipoDocumento;
	}

	public void setIdTipoDocumento(String idTipoDocumento) {
		this.idTipoDocumento = idTipoDocumento;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getClientes() {
		return this.clientes;
	}

	public void setClientes(Set clientes) {
		this.clientes = clientes;
	}

}
