package co.edu.campusucc.sd.modelo;
// Generated 23/05/2020 02:30:18 PM by Hibernate Tools 5.4.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TipoCuenta generated by hbm2java
 */
public class TipoCuenta implements java.io.Serializable {

	private String idTipoCuenta;
	private String nombre;
	private Set cuentas = new HashSet(0);

	public TipoCuenta() {
	}

	public TipoCuenta(String idTipoCuenta, String nombre) {
		this.idTipoCuenta = idTipoCuenta;
		this.nombre = nombre;
	}

	public TipoCuenta(String idTipoCuenta, String nombre, Set cuentas) {
		this.idTipoCuenta = idTipoCuenta;
		this.nombre = nombre;
		this.cuentas = cuentas;
	}

	public String getIdTipoCuenta() {
		return this.idTipoCuenta;
	}

	public void setIdTipoCuenta(String idTipoCuenta) {
		this.idTipoCuenta = idTipoCuenta;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Set cuentas) {
		this.cuentas = cuentas;
	}

}
