package co.edu.campusucc.sd.modelo;
// Generated 23/05/2020 02:30:18 PM by Hibernate Tools 5.4.7.Final

import java.util.Date;

/**
 * Transferencias generated by hbm2java
 */
public class Transferencias implements java.io.Serializable {

	private String idTransferencias;
	private Cuenta cuenta;
	private String montoDinero;
	private String referenciaClienteDestino;
	private int comision;
	private Date fechaHora;
	private String referenciaClienteRemitente;

	public Transferencias() {
	}

	public Transferencias(String idTransferencias, Cuenta cuenta, String montoDinero, String referenciaClienteDestino,
			int comision, Date fechaHora, String referenciaClienteRemitente) {
		this.idTransferencias = idTransferencias;
		this.cuenta = cuenta;
		this.montoDinero = montoDinero;
		this.referenciaClienteDestino = referenciaClienteDestino;
		this.comision = comision;
		this.fechaHora = fechaHora;
		this.referenciaClienteRemitente = referenciaClienteRemitente;
	}

	public String getIdTransferencias() {
		return this.idTransferencias;
	}

	public void setIdTransferencias(String idTransferencias) {
		this.idTransferencias = idTransferencias;
	}

	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public String getMontoDinero() {
		return this.montoDinero;
	}

	public void setMontoDinero(String montoDinero) {
		this.montoDinero = montoDinero;
	}

	public String getReferenciaClienteDestino() {
		return this.referenciaClienteDestino;
	}

	public void setReferenciaClienteDestino(String referenciaClienteDestino) {
		this.referenciaClienteDestino = referenciaClienteDestino;
	}

	public int getComision() {
		return this.comision;
	}

	public void setComision(int comision) {
		this.comision = comision;
	}

	public Date getFechaHora() {
		return this.fechaHora;
	}

	public void setFechaHora(Date fechaHora) {
		this.fechaHora = fechaHora;
	}

	public String getReferenciaClienteRemitente() {
		return this.referenciaClienteRemitente;
	}

	public void setReferenciaClienteRemitente(String referenciaClienteRemitente) {
		this.referenciaClienteRemitente = referenciaClienteRemitente;
	}

}
